### ISSUE TITLE
Not support antiqueatlas 4 1.1.0 in 1.20.1

### ISSUE THREAD

**Issue by SettingDust** [sleepingdragoninn/surveystones#1]
![图片](https://github.com/sisby-folk/antique-fwaystones/assets/19922286/edf19249-c18a-42d9-83ff-21aa5b24fb48)

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install antiqueatlas, version 0.8.0-4+fabric-1.19 or later.
More details:
	 - Mod 'Antique Fwaystones' (antique-fwaystones) 1.0.3+1.19 requires version 0.8.0-4+fabric-1.19 or later of antiqueatlas, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by sleepingdragoninn** [comment]
fwaystones doesn't support AA4 1.x yet, use 0.x until we make a new release

**Comment by sleepingdragoninn** [comment]
done in 1.1.0
