### ISSUE TITLE
Invalid player data trying to load a save.

### ISSUE THREAD

**Issue by murphy-slaw** [sleepingdragoninn/surveystones#3]
Minecraft 1.20.1
Fabric Waystones 3.3.2+mc1.20.1
Antique Atlas 4 2.6.0+1.20
Surveystones 1.3.0+1.20

When attempting to load a world with Fabric Waystones, Surveystones, and Antique Atlas 4, the game loads the world and then chokes trying to load my playerdata due to invalid NBT data:

```
[17:36:48] [Server thread/ERROR]: Couldn't place player in world
net.minecraft.class_148: Loading entity NBT
	at net.minecraft.class_1297.method_5651(class_1297.java:1939) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14600(class_3324.java:375) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$boj000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "folk.sisby.surveyor.client.SurveyorNetworkHandler.getProfile()" because the return value of "net.minecraft.class_310.method_1562()" is null
	at folk.sisby.surveyor.client.SurveyorClient.getClientUuid(SurveyorClient.java:119) ~[surveyor-0.3.2+1.20.jar:?]
	at folk.sisby.surveyor.client.SurveyorClient.getExploration(SurveyorClient.java:93) ~[surveyor-0.3.2+1.20.jar:?]
	at folk.sisby.surveyor.client.SurveyorClient.lambda$onInitializeClient$6(SurveyorClient.java:157) ~[surveyor-0.3.2+1.20.jar:?]
	at folk.sisby.surveyor.SurveyorEvents$Invoke.lambda$landmarksAdded$3(SurveyorEvents.java:60) ~[surveyor-0.3.2+1.20.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at folk.sisby.surveyor.SurveyorEvents$Invoke.landmarksAdded(SurveyorEvents.java:60) ~[surveyor-0.3.2+1.20.jar:?]
	at folk.sisby.surveyor.landmark.WorldLandmarks.handleChanged(WorldLandmarks.java:81) ~[surveyor-0.3.2+1.20.jar:?]
	at folk.sisby.surveyor.landmark.WorldLandmarks.put(WorldLandmarks.java:102) ~[surveyor-0.3.2+1.20.jar:?]
	at folk.sisby.surveystones.FwaystoneEvents.discoverWaystone(FwaystoneEvents.java:26) ~[surveystones-1.3.0+1.20.jar:?]
	at wraith.fwaystones.integration.event.WaystoneEvents.lambda$static$0(WaystoneEvents.java:16) ~[wraith-waystones-3.3.2+mc1.20.1.jar:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at wraith.fwaystones.integration.event.WaystoneEvents.lambda$static$1(WaystoneEvents.java:16) ~[wraith-waystones-3.3.2+mc1.20.1.jar:?]
	at net.minecraft.class_1657.md2055a5$fwaystones$lambda$fabricWaystones$fromTagW$2$2(class_1657.java:11116) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_1657.fabricWaystones$fromTagW(class_1657.java:11113) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.handler$cen000$fwaystones$readCustomDataFromNbt(class_1657.java:11093) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5749(class_1657.java:846) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_5749(class_3222.java:327) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1930) ~[client-intermediary.jar:?]
	... 14 more
[17:36:48] [Server thread/INFO]: com.mojang.authlib.GameProfile@64b6180[id=f0726398-654d-473c-af31-b0a210214fd4,name=murphy_slaw_mc,properties={},legacy=false] (local:E:324964f5) lost connection: Invalid player data
```

My player data attached (zipped because GitHub won't allow me to upload a .dat file)
[f0726398-654d-473c-af31-b0a210214fd4.dat.zip](https://github.com/sisby-folk/surveystones/files/15123696/f0726398-654d-473c-af31-b0a210214fd4.dat.zip)

**Comment by murphy-slaw** [comment]
Invalid player data only occurs on saves where at least one waystone has been activated. Confirmed on a fresh install with no other mods besides AA, Surveystones, and Fabric Waystones. Does not occur if Blay's Waystones are installed instead of Fabric Waystones.

**Comment by sleepingdragoninn** [comment]
This looks like a race condition where the add waystone event is being called too early for the client to handle - I'll have a peek.

Reproduced: https://mclo.gs/hyFOcvb

**Comment by sleepingdragoninn** [comment]
Should be fixed by https://modrinth.com/mod/surveyor/version/0.3.4+1.20 - let me know!

**Comment by murphy-slaw** [comment]
Yep, Surveyor 0.3.4 fixes it. Thanks!
